import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    backgroundColor: '#353A45',
  },
  box: {
    borderRadius: 40,
    marginTop: 25,
    alignItems: 'center',
    justifyContent: 'center',
    width: 339,
    height: 266,
  },
  boxShadow: {
    shadowOffset: {width: -8, height: -8},
    shadowOpacity: 1,
    shadowRadius: 16,
    borderRadius: 37.5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#353A45',
    width: 334,
    height: 261,
  },
  topContainer: {
    width: '100%',
    height: 608,
  },
  back: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '#353A45',
  },
  bottomContainer: {
    height: 104,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  scrollBottom: {
    height: 25,
  },
  scrollTop: {
    height: 10,
  },
  title: {
    width: '100%',
    textShadowColor: 'black',
    textShadowRadius: 5,
    textShadowOffset: {width: 2, height: 2},
    color: '#FDD400',
    height: 69,
    fontSize: 25,
    fontFamily: 'chakraPetchBold',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  pageText: {
    width: '100%',
    textShadowColor: 'black',
    textShadowRadius: 5,
    textShadowOffset: {width: 2, height: 2},
    color: '#FF008A',
    fontSize: 36,
    fontFamily: 'chakraPetchBold',
    textAlign: 'center',
  },
  image: {
    marginTop: 13,
    height: 159,
    width: 159,
    borderRadius: 79.5,
    borderWidth: 4,
    borderColor: 'white',
  },
  image2: {
    alignSelf: 'center',
    borderColor: 'black',
    borderWidth: 4,
    height: 200,
    width: 300,
    borderRadius: 37.5,
    margin: 10,
  },
  curPage: {
    shadowOffset: {width: -4, height: -4},
    shadowOpacity: 1,
    shadowRadius: 8,
    height: 63,
    width: 63,
    marginTop: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 31.5,
    backgroundColor: '#353A45',
  },
  buttonShadow: {
    shadowOffset: {width: -7, height: -7},
    shadowOpacity: 1,
    marginTop: 16,
    shadowRadius: 14,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#353A45',
    width: 112,
    height: 63,
  },
  buttonText: {
    width: '100%',
    textShadowColor: 'black',
    textShadowRadius: 5,
    textShadowOffset: {width: 2, height: 2},
    color: '#FDD400',
    fontFamily: 'chakraPetchBold',
    fontSize: 18,
    textAlign: 'center',
  },
});
